/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 2367f203948232d5103529cf4d25645f)
interface __BaseEnv_Env {
	FEISHU_APP_ID: string;
	FEISHU_APP_SECRET: string;
	FEISHU_ENCRYPT_KEY: string;
	FEISHU_VERIFICATION_TOKEN: string;
	WECHAT_COOKIE_SECRET: string;
	OCR_API_PRIVATE_KEY: string;
	WOS_API_SALT_CN: string;
	WOS_API_SALT_INT: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FEISHU_APP_ID" | "FEISHU_APP_SECRET" | "FEISHU_ENCRYPT_KEY" | "FEISHU_VERIFICATION_TOKEN" | "WECHAT_COOKIE_SECRET" | "OCR_API_PRIVATE_KEY" | "WOS_API_SALT_CN" | "WOS_API_SALT_INT">> {}
}
