/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d60338c90192ec2020d15a6961ad94e5)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ILINK_CHANNEL_VERSION: "2.4.3";
	FEISHU_APP_ID: string;
	FEISHU_APP_SECRET: string;
	FEISHU_ENCRYPT_KEY: string;
	FEISHU_VERIFICATION_TOKEN: string;
	WECHAT_COOKIE_SECRET: string;
	OCR_API_PRIVATE_KEY: string;
	WOS_API_SALT_CN: string;
	WOS_API_SALT_INT: string;
	IDENTITY_MAPPER: DurableObjectNamespace<import("./src/index").IdentityMapper>;
	WECHAT_BOT_AGENT: DurableObjectNamespace /* WeChatBotAgent */;
	WECHAT_QR_CODE_AGENT: DurableObjectNamespace /* WeChatQRCodeAgent */;
	ROUTER: Service<typeof import("./src/index").RouterEntrypoint>;
	ADMIN: Service<typeof import("./src/index").AdminEntrypoint>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "IdentityMapper" | "WeChatBotAgent" | "WeChatQRCodeAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ILINK_CHANNEL_VERSION" | "FEISHU_APP_ID" | "FEISHU_APP_SECRET" | "FEISHU_ENCRYPT_KEY" | "FEISHU_VERIFICATION_TOKEN" | "WECHAT_COOKIE_SECRET" | "OCR_API_PRIVATE_KEY" | "WOS_API_SALT_CN" | "WOS_API_SALT_INT">> {}
}
